service: http

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'prod'}
  region: us-east-1
  timeout: 10 #Default Lambda timeout
  memorySize: 128 #Default Lambda Memory Size
  versionFunctions: false # No functions versioning
  package:
    excludeDevDependencies: true
    exclude:
      - .git/**
      - .vscode/**
      - .test/**

  environment: #Global Environment variables
    ${file(./configs/${self:provider.stage}.yml)}

custom:
  region: ${self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:custom.stage}-${self:service}
  process: ${self:custom.prefix}-process
  config: ${self:custom.prefix}-config

  serverless-offline:
    host: "0.0.0.0"

functions: ${file(serverless-dynamic.js)}
